// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:1bae8035-2dc7-4760-8495-8992518edb9e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_s7vYmhNYl",
    "aws_user_pools_web_client_id": "2pl682besee1djlghkl9q9rsnr",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "donor-ionic",
            "region": "eu-west-1"
        },
        {
            "tableName": "points-ionic",
            "region": "eu-west-1"
        },
        {
            "tableName": "records-ionic",
            "region": "eu-west-1"
        },
        {
            "tableName": "hospitals-ionic",
            "region": "eu-west-1"
        },
        {
            "tableName": "campaigns-ionic",
            "region": "eu-west-1"
        },
        {
            "tableName": "donations-ionic",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "donor",
            "endpoint": "https://kmf86bfju3.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        },
        {
            "name": "points",
            "endpoint": "https://u957tmcv2l.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        },
        {
            "name": "recordsapi",
            "endpoint": "https://kcg2fgjnrb.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        },
        {
            "name": "hospitalsapi",
            "endpoint": "https://sg3oj1p8ac.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        },
        {
            "name": "campaignsapi",
            "endpoint": "https://h1pd72g0f7.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        },
        {
            "name": "donationsapi",
            "endpoint": "https://frymkfagz2.execute-api.eu-west-1.amazonaws.com/ionic",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
